import { randomUUID } from 'node:crypto';
import ImageKit from 'imagekit';
import { ProviderError, isPermanentStatus, safeMessage, withTimeout } from './errors.js';

/**
 * Object storage behind one interface. The domain stores metadata (files
 * table) and depends on this interface only; provider SDKs stay here.
 * An S3-compatible adapter can implement the same contract later.
 */

export type StorageProviderName = 'imagekit' | 'memory';

export interface StoredObject {
  provider: StorageProviderName;
  providerFileId: string;
  url: string;
  size: number;
}

export interface FileStorage {
  readonly provider: StorageProviderName;
  /** `key` is generated by the caller (never user input); `folder` + `name` form it. */
  put(input: {
    buffer: Buffer;
    folder: string;
    name: string;
    tags: string[];
  }): Promise<StoredObject>;
  /** Idempotent: deleting a missing object succeeds. */
  delete(providerFileId: string): Promise<void>;
}

export interface ImageKitConfig {
  publicKey: string;
  privateKey: string;
  urlEndpoint: string;
  timeoutMs?: number;
}

const statusOf = (error: unknown) =>
  (error as { $ResponseMetadata?: { statusCode?: number } })?.$ResponseMetadata?.statusCode ??
  (error as { statusCode?: number })?.statusCode;

export function createImageKitStorage(config: ImageKitConfig): FileStorage {
  let client: ImageKit | undefined;
  const sdk = () =>
    (client ??= new ImageKit({
      publicKey: config.publicKey,
      privateKey: config.privateKey,
      urlEndpoint: config.urlEndpoint,
    }));
  const timeoutMs = config.timeoutMs ?? 30_000;
  return {
    provider: 'imagekit',
    async put({ buffer, folder, name, tags }) {
      try {
        const response = await withTimeout(
          sdk().upload({ file: buffer, fileName: name, folder, useUniqueFileName: false, tags }),
          timeoutMs,
          'ImageKit upload',
        );
        return {
          provider: 'imagekit',
          providerFileId: response.fileId,
          url: response.url,
          size: response.size,
        };
      } catch (error) {
        if (error instanceof ProviderError) throw error;
        const status = statusOf(error);
        throw new ProviderError(
          'STORAGE_UPLOAD_FAILED',
          safeMessage(error),
          isPermanentStatus(status),
          {
            cause: error,
          },
        );
      }
    },
    async delete(providerFileId) {
      try {
        await withTimeout(sdk().deleteFile(providerFileId), timeoutMs, 'ImageKit delete');
      } catch (error) {
        if (error instanceof ProviderError) throw error;
        const status = statusOf(error);
        if (status === 404) return; // already gone: deletion is idempotent
        throw new ProviderError(
          'STORAGE_DELETE_FAILED',
          safeMessage(error),
          isPermanentStatus(status),
          {
            cause: error,
          },
        );
      }
    },
  };
}

/** In-process storage for development and tests (never used when NODE_ENV=production). */
export function createMemoryStorage(): FileStorage & { objects: Map<string, Buffer> } {
  const objects = new Map<string, Buffer>();
  return {
    provider: 'memory',
    objects,
    async put({ buffer, folder, name }) {
      const id = randomUUID();
      objects.set(id, buffer);
      return {
        provider: 'memory',
        providerFileId: id,
        url: `memory://${folder}/${name}`,
        size: buffer.length,
      };
    },
    async delete(providerFileId) {
      objects.delete(providerFileId);
    },
  };
}
