import { createHmac, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import ImageKit from 'imagekit';
import { ProviderError, isPermanentStatus, safeMessage, withTimeout } from './errors.js';

/**
 * Object storage behind one interface. The domain stores metadata (files
 * table) and depends on this interface only; provider SDKs stay here.
 * An S3-compatible adapter can implement the same contract later.
 */

export type StorageProviderName = 'imagekit' | 'memory';

export interface StoredObject {
  provider: StorageProviderName;
  providerFileId: string;
  url: string;
  size: number;
}

export interface FileStorage {
  readonly provider: StorageProviderName;
  /** `key` is generated by the caller (never user input); `folder` + `name` form it. */
  put(input: {
    buffer: Buffer;
    folder: string;
    name: string;
    tags: string[];
  }): Promise<StoredObject>;
  /** Idempotent: deleting a missing object succeeds. */
  delete(providerFileId: string): Promise<void>;
  /**
   * Short-lived URL for reading the object. Only issued by the API after an
   * authorization check; it expires after `expiresInSeconds`.
   */
  signedUrl(object: { url: string; providerFileId: string }, expiresInSeconds: number): string;
}

export interface ImageKitConfig {
  publicKey: string;
  privateKey: string;
  urlEndpoint: string;
  timeoutMs?: number;
}

const statusOf = (error: unknown) =>
  (error as { $ResponseMetadata?: { statusCode?: number } })?.$ResponseMetadata?.statusCode ??
  (error as { statusCode?: number })?.statusCode;

export function createImageKitStorage(config: ImageKitConfig): FileStorage {
  let client: ImageKit | undefined;
  const sdk = () =>
    (client ??= new ImageKit({
      publicKey: config.publicKey,
      privateKey: config.privateKey,
      urlEndpoint: config.urlEndpoint,
    }));
  const timeoutMs = config.timeoutMs ?? 30_000;
  return {
    provider: 'imagekit',
    async put({ buffer, folder, name, tags }) {
      try {
        const response = await withTimeout(
          sdk().upload({ file: buffer, fileName: name, folder, useUniqueFileName: false, tags }),
          timeoutMs,
          'ImageKit upload',
        );
        return {
          provider: 'imagekit',
          providerFileId: response.fileId,
          url: response.url,
          size: response.size,
        };
      } catch (error) {
        if (error instanceof ProviderError) throw error;
        const status = statusOf(error);
        throw new ProviderError(
          'STORAGE_UPLOAD_FAILED',
          safeMessage(error),
          isPermanentStatus(status),
          {
            cause: error,
          },
        );
      }
    },
    signedUrl(object, expiresInSeconds) {
      // Enforced by ImageKit once "Restrict unsigned URLs" is enabled on the account (operator action).
      return sdk().url({ src: object.url, signed: true, expireSeconds: expiresInSeconds });
    },
    async delete(providerFileId) {
      try {
        await withTimeout(sdk().deleteFile(providerFileId), timeoutMs, 'ImageKit delete');
      } catch (error) {
        if (error instanceof ProviderError) throw error;
        const status = statusOf(error);
        if (status === 404) return; // already gone: deletion is idempotent
        throw new ProviderError(
          'STORAGE_DELETE_FAILED',
          safeMessage(error),
          isPermanentStatus(status),
          {
            cause: error,
          },
        );
      }
    },
  };
}

/** In-process storage for development and tests (never used when NODE_ENV=production). */
export function createMemoryStorage(
  options: { signingSecret?: string; now?: () => number } = {},
): FileStorage & {
  objects: Map<string, Buffer>;
  /** Mirrors provider-side enforcement: true only for an unexpired, untampered signed URL. */
  verifySignedUrl(url: string): boolean;
} {
  const objects = new Map<string, Buffer>();
  const secret = options.signingSecret ?? randomBytes(32).toString('hex');
  const now = options.now ?? Date.now;
  const sign = (base: string, expires: number) =>
    createHmac('sha256', secret).update(`${base}\n${expires}`).digest('hex');
  return {
    provider: 'memory',
    objects,
    signedUrl(object, expiresInSeconds) {
      const expires = Math.floor(now() / 1000) + expiresInSeconds;
      return `${object.url}?expires=${expires}&signature=${sign(object.url, expires)}`;
    },
    verifySignedUrl(url) {
      const match = /^(.*)\?expires=(\d+)&signature=([0-9a-f]{64})$/.exec(url);
      if (!match) return false;
      const [, base, rawExpires, signature] = match as unknown as [string, string, string, string];
      const expires = Number(rawExpires);
      if (expires * 1000 <= now()) return false;
      const expected = Buffer.from(sign(base, expires));
      const given = Buffer.from(signature);
      return expected.length === given.length && timingSafeEqual(expected, given);
    },
    async put({ buffer, folder, name }) {
      const id = randomUUID();
      objects.set(id, buffer);
      return {
        provider: 'memory',
        providerFileId: id,
        url: `memory://${folder}/${name}`,
        size: buffer.length,
      };
    },
    async delete(providerFileId) {
      objects.delete(providerFileId);
    },
  };
}
